---
- name: Configure ptmd from local topology.dot
  copy:
    src: '{{ ptm.topology if ptm.topology is defined else "topology.dot" }}'
    dest: /etc/ptm.d/topology.dot
  notify:
    - restart ptmd

- meta: flush_handlers
