---
devices:
  server01:
    bond:
      vlan: 10
      ip: 10.1.10.101/24
      route:
        dest: 10.0.0.0/8
        nexthop: 10.1.10.1
  server02:
    bond:
      vlan: 20
      ip: 10.1.20.102/24
      route:
        dest: 10.0.0.0/8
        nexthop: 10.1.20.1
  server03:
    bond:
      vlan: 30
      ip: 10.1.30.103/24
      route:
        dest: 10.0.0.0/8
        nexthop: 10.1.30.1

