---
- hosts: spine leaf
  become: yes
  roles:
    - { role: hostname, tags: ['hostname'] }
    - { role: motd, tags: ['motd'] }
    - { role: dns, tags: ['dns'] }
    - { role: ssh, tags: ['ssh'] }
    - { role: ptm, tags: ['ptm'] }
    - { role: snmp, tags: ['snmp'] }
    - { role: syslog, tags: ['syslog'] }
    - { role: ntp, tags: ['ntp'] }
    - { role: tacacs_client, tags: ['tacacs_client'] }
    - { role: interfaces, tags: ['interfaces'] }
    - { role: frr, tags: ['frr'] }
    - { role: backup, tags: ['backup'] }

- name: fix-quick
  hosts: leaf01
  become: yes
  tasks:
  - name: Configure server bond on leaf01
    nclu:
      commands:
        - add bond bond0 bond slaves swp1
        - add bridge bridge ports bond0
        - add bond bond0 bridge access 10
      commit: true

- name: quick-fix
  hosts: leaf02
  become: yes
  tasks:
  - name: Configure server bonds on leaf02
    nclu:
      commands:
        - add bond bond0 bond slaves swp1
        - add bridge bridge ports bond0
        - add bond bond0 bridge access 20
        - add bond bond1 bond slaves swp2
        - add bridge bridge ports bond1
        - add bond bond1 bridge access 30
      commit: true

- hosts: host
  become: yes
  roles:
    - { role: servers, tags: ['servers'] }
    - { role: backup, tags: ['backup'] }
    #- { role: netq_servers, tags: ['netq_servers'] }

- hosts: localhost
  become: yes
  roles:
    - { role: tacacs_server, tags: ['tacacs_server'] }
    #- { role: netq_servers, tags: ['netq_servers'] }
