---
- hosts: spine leaf border
  become: yes
  roles:
    - { role: hostname, tags: ['hostname'] }
    - { role: motd, tags: ['motd'] }
    - { role: dns, tags: ['dns'] }
    - { role: ssh, tags: ['ssh'] }
    - { role: ptm, tags: ['ptm'] }
    - { role: snmp, tags: ['snmp'] }
    - { role: syslog, tags: ['syslog'] }
    - { role: ntp, tags: ['ntp'] }
    - { role: tacacs_client, tags: ['tacacs_client'] }
    - { role: interfaces, tags: ['interfaces'] }
    - { role: frr, tags: ['frr'] }
    - { role: backup, tags: ['backup'] }
    #- { role: netq_switch, tags: ['netq_switch'] }

- hosts: fw
  become: yes
  roles:
    - { role: firewalls, tags: ['fw'] }
    - { role: backup, tags: ['backup'] }
    #- { role: netq_switch, tags: ['netq_switch'] }

- hosts: host
  become: yes
  roles:
    - { role: servers, tags: ['servers'] }
    - { role: backup, tags: ['backup'] }
    #- { role: netq_servers, tags: ['netq_servers'] }

- hosts: localhost
  become: yes
  roles:
    - { role: tacacs_server, tags: ['tacacs_server'] }
    #- { role: netq_servers, tags: ['netq_servers'] }
